#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MyCryptos.Droid.Resource", IsApplication=true)]

namespace MyCryptos.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030002
			public const int accent = 2130903042;
			
			// aapt resource value: 0x7f030000
			public const int primary = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int primaryDark = 2130903041;
			
			// aapt resource value: 0x7f030003
			public const int window_background = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accounts = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkmark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int coins = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int down = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int hamburger = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int more = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int settings = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sources = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tags = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int up = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int MyActionBar = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int MyCryptosTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
