#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyCC.Forms.Android.Resource", IsApplication=true)]

namespace MyCC.Forms.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiCentered = global::MyCC.Forms.Android.Resource.Attribute.vpiCentered;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiCirclePageIndicatorStyle = global::MyCC.Forms.Android.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiFillColor = global::MyCC.Forms.Android.Resource.Attribute.vpiFillColor;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiOrientation = global::MyCC.Forms.Android.Resource.Attribute.vpiOrientation;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiPageColor = global::MyCC.Forms.Android.Resource.Attribute.vpiPageColor;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiRadius = global::MyCC.Forms.Android.Resource.Attribute.vpiRadius;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiSnap = global::MyCC.Forms.Android.Resource.Attribute.vpiSnap;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiStrokeColor = global::MyCC.Forms.Android.Resource.Attribute.vpiStrokeColor;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiStrokeWidth = global::MyCC.Forms.Android.Resource.Attribute.vpiStrokeWidth;
			global::CarouselView.FormsPlugin.Android.Resource.Boolean.default_circle_indicator_centered = global::MyCC.Forms.Android.Resource.Boolean.default_circle_indicator_centered;
			global::CarouselView.FormsPlugin.Android.Resource.Boolean.default_circle_indicator_snap = global::MyCC.Forms.Android.Resource.Boolean.default_circle_indicator_snap;
			global::CarouselView.FormsPlugin.Android.Resource.Color.default_circle_indicator_fill_color = global::MyCC.Forms.Android.Resource.Color.default_circle_indicator_fill_color;
			global::CarouselView.FormsPlugin.Android.Resource.Color.default_circle_indicator_page_color = global::MyCC.Forms.Android.Resource.Color.default_circle_indicator_page_color;
			global::CarouselView.FormsPlugin.Android.Resource.Color.default_circle_indicator_stroke_color = global::MyCC.Forms.Android.Resource.Color.default_circle_indicator_stroke_color;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__background_holo_dark = global::MyCC.Forms.Android.Resource.Color.vpi__background_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__background_holo_light = global::MyCC.Forms.Android.Resource.Color.vpi__background_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::MyCC.Forms.Android.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::MyCC.Forms.Android.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_holo_dark = global::MyCC.Forms.Android.Resource.Color.vpi__bright_foreground_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_holo_light = global::MyCC.Forms.Android.Resource.Color.vpi__bright_foreground_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::MyCC.Forms.Android.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::MyCC.Forms.Android.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Dimension.default_circle_indicator_radius = global::MyCC.Forms.Android.Resource.Dimension.default_circle_indicator_radius;
			global::CarouselView.FormsPlugin.Android.Resource.Dimension.default_circle_indicator_stroke_width = global::MyCC.Forms.Android.Resource.Dimension.default_circle_indicator_stroke_width;
			global::CarouselView.FormsPlugin.Android.Resource.Id.horizontal = global::MyCC.Forms.Android.Resource.Id.horizontal;
			global::CarouselView.FormsPlugin.Android.Resource.Id.indicator = global::MyCC.Forms.Android.Resource.Id.indicator;
			global::CarouselView.FormsPlugin.Android.Resource.Id.pager = global::MyCC.Forms.Android.Resource.Id.pager;
			global::CarouselView.FormsPlugin.Android.Resource.Id.title = global::MyCC.Forms.Android.Resource.Id.title;
			global::CarouselView.FormsPlugin.Android.Resource.Id.vertical = global::MyCC.Forms.Android.Resource.Id.vertical;
			global::CarouselView.FormsPlugin.Android.Resource.Integer.default_circle_indicator_orientation = global::MyCC.Forms.Android.Resource.Integer.default_circle_indicator_orientation;
			global::CarouselView.FormsPlugin.Android.Resource.Layout.vertical_viewpager = global::MyCC.Forms.Android.Resource.Layout.vertical_viewpager;
			global::CarouselView.FormsPlugin.Android.Resource.Layout.viewpager = global::MyCC.Forms.Android.Resource.Layout.viewpager;
			global::CarouselView.FormsPlugin.Android.Resource.Style.Theme_PageIndicatorDefaults = global::MyCC.Forms.Android.Resource.Style.Theme_PageIndicatorDefaults;
			global::CarouselView.FormsPlugin.Android.Resource.Style.Widget = global::MyCC.Forms.Android.Resource.Style.Widget;
			global::CarouselView.FormsPlugin.Android.Resource.Style.Widget_CirclePageIndicator = global::MyCC.Forms.Android.Resource.Style.Widget_CirclePageIndicator;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiCentered = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiCentered;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiFillColor = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiFillColor;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiOrientation = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiOrientation;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiPageColor = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiPageColor;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiRadius = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiRadius;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiSnap = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiSnap;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiStrokeColor = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiStrokeColor;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiStrokeWidth = global::MyCC.Forms.Android.Resource.Styleable.CirclePageIndicator_vpiStrokeWidth;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.ViewPagerIndicator = global::MyCC.Forms.Android.Resource.Styleable.ViewPagerIndicator;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::MyCC.Forms.Android.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::MyCC.Forms.Android.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::MyCC.Forms.Android.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::MyCC.Forms.Android.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::MyCC.Forms.Android.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::MyCC.Forms.Android.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::MyCC.Forms.Android.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::MyCC.Forms.Android.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::MyCC.Forms.Android.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::MyCC.Forms.Android.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::MyCC.Forms.Android.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::MyCC.Forms.Android.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::MyCC.Forms.Android.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::MyCC.Forms.Android.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::MyCC.Forms.Android.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::MyCC.Forms.Android.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::MyCC.Forms.Android.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::MyCC.Forms.Android.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::MyCC.Forms.Android.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::MyCC.Forms.Android.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::MyCC.Forms.Android.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::MyCC.Forms.Android.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::MyCC.Forms.Android.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::MyCC.Forms.Android.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::MyCC.Forms.Android.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::MyCC.Forms.Android.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::MyCC.Forms.Android.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::MyCC.Forms.Android.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::MyCC.Forms.Android.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::MyCC.Forms.Android.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::MyCC.Forms.Android.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::MyCC.Forms.Android.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::MyCC.Forms.Android.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::MyCC.Forms.Android.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::MyCC.Forms.Android.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::MyCC.Forms.Android.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::MyCC.Forms.Android.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::MyCC.Forms.Android.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::MyCC.Forms.Android.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::MyCC.Forms.Android.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::MyCC.Forms.Android.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::MyCC.Forms.Android.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::MyCC.Forms.Android.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::MyCC.Forms.Android.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::MyCC.Forms.Android.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::MyCC.Forms.Android.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::MyCC.Forms.Android.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::MyCC.Forms.Android.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::MyCC.Forms.Android.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::MyCC.Forms.Android.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::MyCC.Forms.Android.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::MyCC.Forms.Android.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::MyCC.Forms.Android.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::MyCC.Forms.Android.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::MyCC.Forms.Android.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::MyCC.Forms.Android.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::MyCC.Forms.Android.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::MyCC.Forms.Android.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::MyCC.Forms.Android.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::ModernHttpClient.Resource.String.library_name = global::MyCC.Forms.Android.Resource.String.library_name;
			global::PCLCrypto.Resource.String.ApplicationName = global::MyCC.Forms.Android.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::MyCC.Forms.Android.Resource.String.Hello;
			global::Plugin.Fingerprint.Resource.Drawable.fingerprint_white = global::MyCC.Forms.Android.Resource.Drawable.fingerprint_white;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_btnCancel = global::MyCC.Forms.Android.Resource.Id.fingerprint_btnCancel;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_btnFallback = global::MyCC.Forms.Android.Resource.Id.fingerprint_btnFallback;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_imgFingerprint = global::MyCC.Forms.Android.Resource.Id.fingerprint_imgFingerprint;
			global::Plugin.Fingerprint.Resource.Id.fingerprint_txtReason = global::MyCC.Forms.Android.Resource.Id.fingerprint_txtReason;
			global::Plugin.Fingerprint.Resource.Layout.FingerprintDialog = global::MyCC.Forms.Android.Resource.Layout.FingerprintDialog;
			global::XLabs.Forms.Droid.Resource.Color.calendar_active_month_bg = global::MyCC.Forms.Android.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_bg = global::MyCC.Forms.Android.Resource.Color.calendar_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_divider = global::MyCC.Forms.Android.Resource.Color.calendar_divider;
			global::XLabs.Forms.Droid.Resource.Color.calendar_highlighted_day_bg = global::MyCC.Forms.Android.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_inactive_month_bg = global::MyCC.Forms.Android.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_day_bg = global::MyCC.Forms.Android.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_selected_range_bg = global::MyCC.Forms.Android.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_active = global::MyCC.Forms.Android.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_inactive = global::MyCC.Forms.Android.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selected = global::MyCC.Forms.Android.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_selector = global::MyCC.Forms.Android.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Droid.Resource.Color.calendar_text_unselectable = global::MyCC.Forms.Android.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_day_headers_paddingbottom = global::MyCC.Forms.Android.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_title_bottommargin = global::MyCC.Forms.Android.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_month_topmargin = global::MyCC.Forms.Android.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_medium = global::MyCC.Forms.Android.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Droid.Resource.Dimension.calendar_text_small = global::MyCC.Forms.Android.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Droid.Resource.Drawable.ad16 = global::MyCC.Forms.Android.Resource.Drawable.ad16;
			global::XLabs.Forms.Droid.Resource.Drawable.calendar_bg_selector = global::MyCC.Forms.Android.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Droid.Resource.Id.calendar_grid = global::MyCC.Forms.Android.Resource.Id.calendar_grid;
			global::XLabs.Forms.Droid.Resource.Id.calendar_view = global::MyCC.Forms.Android.Resource.Id.calendar_view;
			global::XLabs.Forms.Droid.Resource.Id.calendarr_pager = global::MyCC.Forms.Android.Resource.Id.calendarr_pager;
			global::XLabs.Forms.Droid.Resource.Id.left_arrow = global::MyCC.Forms.Android.Resource.Id.left_arrow;
			global::XLabs.Forms.Droid.Resource.Id.right_arrow = global::MyCC.Forms.Android.Resource.Id.right_arrow;
			global::XLabs.Forms.Droid.Resource.Id.title = global::MyCC.Forms.Android.Resource.Id.title;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager = global::MyCC.Forms.Android.Resource.Layout.calendar_pager;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_pager_layout = global::MyCC.Forms.Android.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Droid.Resource.Layout.calendar_picker = global::MyCC.Forms.Android.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Droid.Resource.Layout.dialog = global::MyCC.Forms.Android.Resource.Layout.dialog;
			global::XLabs.Forms.Droid.Resource.Layout.month = global::MyCC.Forms.Android.Resource.Layout.month;
			global::XLabs.Forms.Droid.Resource.Layout.week = global::MyCC.Forms.Android.Resource.Layout.week;
			global::XLabs.Forms.Droid.Resource.String.ApplicationName = global::MyCC.Forms.Android.Resource.String.ApplicationName;
			global::XLabs.Forms.Droid.Resource.String.Hello = global::MyCC.Forms.Android.Resource.String.Hello;
			global::XLabs.Forms.Droid.Resource.String.day_name_format = global::MyCC.Forms.Android.Resource.String.day_name_format;
			global::XLabs.Forms.Droid.Resource.String.full_date_format = global::MyCC.Forms.Android.Resource.String.full_date_format;
			global::XLabs.Forms.Droid.Resource.String.invalid_date = global::MyCC.Forms.Android.Resource.String.invalid_date;
			global::XLabs.Forms.Droid.Resource.String.library_name = global::MyCC.Forms.Android.Resource.String.library_name;
			global::XLabs.Forms.Droid.Resource.String.month_name_format = global::MyCC.Forms.Android.Resource.String.month_name_format;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell = global::MyCC.Forms.Android.Resource.Style.CalendarCell;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_CalendarDate = global::MyCC.Forms.Android.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Droid.Resource.Style.CalendarCell_DayHeader = global::MyCC.Forms.Android.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Droid.Resource.Style.CalendarTitle = global::MyCC.Forms.Android.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::MyCC.Forms.Android.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::MyCC.Forms.Android.Resource.String.Hello;
			global::ZXing.Net.Mobile.Forms.Android.Resource.Layout.zxingscanneractivitylayout = global::MyCC.Forms.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Net.Mobile.Forms.Android.Resource.Layout.zxingscannerfragmentlayout = global::MyCC.Forms.Android.Resource.Layout.zxingscannerfragmentlayout;
			global::ZXing.Net.Mobile.Forms.Android.Resource.String.library_name = global::MyCC.Forms.Android.Resource.String.library_name;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::MyCC.Forms.Android.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::MyCC.Forms.Android.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::MyCC.Forms.Android.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int vpiCentered = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int vpiFillColor = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int vpiOrientation = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int vpiPageColor = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int vpiRadius = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int vpiSnap = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int vpiStrokeColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int vpiStrokeWidth = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_centered = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_snap = 2131230721;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050022
			public const int accent = 2131034146;
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f050024
			public const int calendar_text_selector = 2131034148;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			// aapt resource value: 0x7f05001d
			public const int default_circle_indicator_fill_color = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int default_circle_indicator_page_color = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int default_circle_indicator_stroke_color = 2131034143;
			
			// aapt resource value: 0x7f05000b
			public const int hockeyapp_background_header = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int hockeyapp_background_light = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hockeyapp_background_white = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hockeyapp_button_background = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hockeyapp_button_background_pressed = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hockeyapp_button_background_selected = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hockeyapp_text_black = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hockeyapp_text_light = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hockeyapp_text_normal = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hockeyapp_text_white = 2131034132;
			
			// aapt resource value: 0x7f050020
			public const int primary = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int primaryDark = 2131034145;
			
			// aapt resource value: 0x7f050015
			public const int vpi__background_holo_dark = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int vpi__background_holo_light = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int vpi__bright_foreground_disabled_holo_light = 2131034138;
			
			// aapt resource value: 0x7f050017
			public const int vpi__bright_foreground_holo_dark = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int vpi__bright_foreground_holo_light = 2131034136;
			
			// aapt resource value: 0x7f05001b
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int vpi__bright_foreground_inverse_holo_light = 2131034140;
			
			// aapt resource value: 0x7f050023
			public const int window_background = 2131034147;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int default_circle_indicator_radius = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int default_circle_indicator_stroke_width = 2131099654;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accounts = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ad16 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int calendar_bg_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int checkmark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int coins = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int delete = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int down = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int edit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int fingerprint = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fingerprint_white = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int flashOff = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int flashOn = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int graph = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int hockeyapp_btn_background = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int info = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int more = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int rate = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int refresh = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int settings = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int sources = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int star = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int starFilled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int table = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int tags = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int up = 2130837530;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0018
			public const int button_add_response = 2131361816;
			
			// aapt resource value: 0x7f0a0013
			public const int button_attachment = 2131361811;
			
			// aapt resource value: 0x7f0a001d
			public const int button_login = 2131361821;
			
			// aapt resource value: 0x7f0a0019
			public const int button_refresh = 2131361817;
			
			// aapt resource value: 0x7f0a0014
			public const int button_send = 2131361812;
			
			// aapt resource value: 0x7f0a0021
			public const int button_update = 2131361825;
			
			// aapt resource value: 0x7f0a0027
			public const int calendar_grid = 2131361831;
			
			// aapt resource value: 0x7f0a0004
			public const int calendar_view = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int calendarr_pager = 2131361794;
			
			// aapt resource value: 0x7f0a002a
			public const int contentFrame = 2131361834;
			
			// aapt resource value: 0x7f0a0009
			public const int fingerprint_btnCancel = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int fingerprint_btnFallback = 2131361802;
			
			// aapt resource value: 0x7f0a0007
			public const int fingerprint_imgFingerprint = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int fingerprint_txtReason = 2131361800;
			
			// aapt resource value: 0x7f0a0000
			public const int horizontal = 2131361792;
			
			// aapt resource value: 0x7f0a0029
			public const int indicator = 2131361833;
			
			// aapt resource value: 0x7f0a000f
			public const int input_email = 2131361807;
			
			// aapt resource value: 0x7f0a0011
			public const int input_message = 2131361809;
			
			// aapt resource value: 0x7f0a000e
			public const int input_name = 2131361806;
			
			// aapt resource value: 0x7f0a001c
			public const int input_password = 2131361820;
			
			// aapt resource value: 0x7f0a0010
			public const int input_subject = 2131361808;
			
			// aapt resource value: 0x7f0a0023
			public const int label_author = 2131361827;
			
			// aapt resource value: 0x7f0a0024
			public const int label_date = 2131361828;
			
			// aapt resource value: 0x7f0a0016
			public const int label_last_updated = 2131361814;
			
			// aapt resource value: 0x7f0a000b
			public const int label_message = 2131361803;
			
			// aapt resource value: 0x7f0a0025
			public const int label_text = 2131361829;
			
			// aapt resource value: 0x7f0a001f
			public const int label_title = 2131361823;
			
			// aapt resource value: 0x7f0a0020
			public const int label_version = 2131361824;
			
			// aapt resource value: 0x7f0a0006
			public const int left_arrow = 2131361798;
			
			// aapt resource value: 0x7f0a0026
			public const int list_attachments = 2131361830;
			
			// aapt resource value: 0x7f0a001a
			public const int list_feedback_messages = 2131361818;
			
			// aapt resource value: 0x7f0a0028
			public const int pager = 2131361832;
			
			// aapt resource value: 0x7f0a0005
			public const int right_arrow = 2131361797;
			
			// aapt resource value: 0x7f0a001b
			public const int text_headline = 2131361819;
			
			// aapt resource value: 0x7f0a0003
			public const int title = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int vertical = 2131361793;
			
			// aapt resource value: 0x7f0a001e
			public const int view_header = 2131361822;
			
			// aapt resource value: 0x7f0a0022
			public const int web_update_details = 2131361826;
			
			// aapt resource value: 0x7f0a0012
			public const int wrapper_attachments = 2131361810;
			
			// aapt resource value: 0x7f0a000d
			public const int wrapper_feedback = 2131361805;
			
			// aapt resource value: 0x7f0a000c
			public const int wrapper_feedback_scroll = 2131361804;
			
			// aapt resource value: 0x7f0a0015
			public const int wrapper_messages = 2131361813;
			
			// aapt resource value: 0x7f0a0017
			public const int wrapper_messages_buttons = 2131361815;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_orientation = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_pager_layout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int calendar_picker = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int dialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int FingerprintDialog = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_activity_expiry_info = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int hockeyapp_activity_feedback = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int hockeyapp_activity_login = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int hockeyapp_activity_update = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int hockeyapp_fragment_update = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int hockeyapp_view_feedback_message = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int month = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int vertical_viewpager = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int viewpager = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int week = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int zxingscanneractivitylayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int zxingscannerfragmentlayout = 2130903056;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_crash_dialog_message = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_crash_dialog_negative_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_crash_dialog_neutral_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_crash_dialog_positive_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_crash_dialog_title = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_dialog_error_message = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_dialog_error_title = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_dialog_negative_button = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_dialog_positive_button = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_download_failed_dialog_message = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_download_failed_dialog_title = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_error_no_network_message = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_expiry_info_text = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_expiry_info_title = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_attach_file = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_attach_picture = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_attachment_button_text = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_attachment_error = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_attachment_loading = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_email_hint = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_failed_text = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_failed_title = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_generic_error = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_last_updated_text = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_message_hint = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_name_hint = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_refresh_button_text = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_response_button_text = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_select_file = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_select_picture = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_send_button_text = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_send_generic_error = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_send_network_error = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_sending_feedback_text = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_feedback_subject_hint = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_feedback_title = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_feedback_validate_email_empty = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_feedback_validate_email_error = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_feedback_validate_name_error = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_feedback_validate_subject_error = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_feedback_validate_text_error = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_login_email_hint = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_login_headline_text = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_login_headline_text_email_only = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_login_login_button_text = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_login_missing_credentials_toast = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_login_password_hint = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_paint_dialog_message = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_paint_dialog_negative_button = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_paint_dialog_neutral_button = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_paint_dialog_positive_button = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_paint_indicator_toast = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_paint_menu_clear = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_paint_menu_save = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_paint_menu_undo = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_permission_dialog_negative_button = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_permission_dialog_positive_button = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_permission_update_message = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_permission_update_title = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int hockeyapp_update_button = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int hockeyapp_update_dialog_message = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int hockeyapp_update_dialog_negative_button = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int hockeyapp_update_dialog_positive_button = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int hockeyapp_update_dialog_title = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int hockeyapp_update_mandatory_toast = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int hockeyapp_update_version_details_label = 2130968653;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070004
			public const int HockeyApp_ButtonStyle = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int HockeyApp_EditTextStyle = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int HockeyApp_SingleLineInputStyle = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int MyActionBar = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int MyCryptosTheme = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int Theme_PageIndicatorDefaults = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int Widget = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int Widget_CirclePageIndicator = 2131165193;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_vpiCentered = 0;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_vpiFillColor = 5;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_vpiOrientation = 2;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_vpiPageColor = 1;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_vpiRadius = 4;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_vpiSnap = 3;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_vpiStrokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_vpiStrokeWidth = 7;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
