// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyCryptos.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18N {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyCryptos.Forms.Resources.I18N", typeof(I18N).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AddCoinTitle {
            get {
                return ResourceManager.GetString("AddCoinTitle", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string AppNameLong {
            get {
                return ResourceManager.GetString("AppNameLong", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string CurrencyExample {
            get {
                return ResourceManager.GetString("CurrencyExample", resourceCulture);
            }
        }
        
        public static string ValueExample {
            get {
                return ResourceManager.GetString("ValueExample", resourceCulture);
            }
        }
        
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        public static string NewStorage {
            get {
                return ResourceManager.GetString("NewStorage", resourceCulture);
            }
        }
        
        public static string DefaultStorage {
            get {
                return ResourceManager.GetString("DefaultStorage", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string LabelExample {
            get {
                return ResourceManager.GetString("LabelExample", resourceCulture);
            }
        }
        
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        public static string NoAccounts {
            get {
                return ResourceManager.GetString("NoAccounts", resourceCulture);
            }
        }
        
        public static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        public static string ReferenceCurrency {
            get {
                return ResourceManager.GetString("ReferenceCurrency", resourceCulture);
            }
        }
        
        public static string AddActionChooseTitle {
            get {
                return ResourceManager.GetString("AddActionChooseTitle", resourceCulture);
            }
        }
        
        public static string AddLocalAccount {
            get {
                return ResourceManager.GetString("AddLocalAccount", resourceCulture);
            }
        }
        
        public static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        public static string ByValue {
            get {
                return ResourceManager.GetString("ByValue", resourceCulture);
            }
        }
        
        public static string ByUnits {
            get {
                return ResourceManager.GetString("ByUnits", resourceCulture);
            }
        }
        
        public static string NoExchangeRateFound {
            get {
                return ResourceManager.GetString("NoExchangeRateFound", resourceCulture);
            }
        }
        
        public static string RefreshingDots {
            get {
                return ResourceManager.GetString("RefreshingDots", resourceCulture);
            }
        }
        
        public static string SortDirection {
            get {
                return ResourceManager.GetString("SortDirection", resourceCulture);
            }
        }
        
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        public static string AutomaticallyRefresh {
            get {
                return ResourceManager.GetString("AutomaticallyRefresh", resourceCulture);
            }
        }
        
        public static string RefreshOnStartup {
            get {
                return ResourceManager.GetString("RefreshOnStartup", resourceCulture);
            }
        }
        
        public static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        public static string SearchCurrencies {
            get {
                return ResourceManager.GetString("SearchCurrencies", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string LocalAccount {
            get {
                return ResourceManager.GetString("LocalAccount", resourceCulture);
            }
        }
        
        public static string DifferentCoinsCount {
            get {
                return ResourceManager.GetString("DifferentCoinsCount", resourceCulture);
            }
        }
        
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        public static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string BittrexAccount {
            get {
                return ResourceManager.GetString("BittrexAccount", resourceCulture);
            }
        }
        
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        public static string SecretApiKey {
            get {
                return ResourceManager.GetString("SecretApiKey", resourceCulture);
            }
        }
        
        public static string AddRepositoryTitle {
            get {
                return ResourceManager.GetString("AddRepositoryTitle", resourceCulture);
            }
        }
        
        public static string Bittrex {
            get {
                return ResourceManager.GetString("Bittrex", resourceCulture);
            }
        }
        
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        public static string GrantAccess {
            get {
                return ResourceManager.GetString("GrantAccess", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string FetchingNoSuccessText {
            get {
                return ResourceManager.GetString("FetchingNoSuccessText", resourceCulture);
            }
        }
        
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        public static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string SelectRepositoryType {
            get {
                return ResourceManager.GetString("SelectRepositoryType", resourceCulture);
            }
        }
        
        public static string BlockExperts {
            get {
                return ResourceManager.GetString("BlockExperts", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        public static string BlockExpertsAccount {
            get {
                return ResourceManager.GetString("BlockExpertsAccount", resourceCulture);
            }
        }
        
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        public static string NoCoins {
            get {
                return ResourceManager.GetString("NoCoins", resourceCulture);
            }
        }
        
        public static string Blockchain {
            get {
                return ResourceManager.GetString("Blockchain", resourceCulture);
            }
        }
        
        public static string BlockchainAccount {
            get {
                return ResourceManager.GetString("BlockchainAccount", resourceCulture);
            }
        }
        
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        public static string Appeareance {
            get {
                return ResourceManager.GetString("Appeareance", resourceCulture);
            }
        }
        
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        public static string AdditionalReferenceCurrency {
            get {
                return ResourceManager.GetString("AdditionalReferenceCurrency", resourceCulture);
            }
        }
        
        public static string AddReferenceCurrency {
            get {
                return ResourceManager.GetString("AddReferenceCurrency", resourceCulture);
            }
        }
        
        public static string PrimaryReferenceCurrency {
            get {
                return ResourceManager.GetString("PrimaryReferenceCurrency", resourceCulture);
            }
        }
        
        public static string ReferenceCurrencies {
            get {
                return ResourceManager.GetString("ReferenceCurrencies", resourceCulture);
            }
        }
        
        public static string Etherchain {
            get {
                return ResourceManager.GetString("Etherchain", resourceCulture);
            }
        }
        
        public static string CryptoId {
            get {
                return ResourceManager.GetString("CryptoId", resourceCulture);
            }
        }
        
        public static string OneAccount {
            get {
                return ResourceManager.GetString("OneAccount", resourceCulture);
            }
        }
        
        public static string OneCoin {
            get {
                return ResourceManager.GetString("OneCoin", resourceCulture);
            }
        }
        
        public static string OneSource {
            get {
                return ResourceManager.GetString("OneSource", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string LocalStorage {
            get {
                return ResourceManager.GetString("LocalStorage", resourceCulture);
            }
        }
        
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        public static string AddWithAddress {
            get {
                return ResourceManager.GetString("AddWithAddress", resourceCulture);
            }
        }
        
        public static string AddWithBittrexAccount {
            get {
                return ResourceManager.GetString("AddWithBittrexAccount", resourceCulture);
            }
        }
        
        public static string Unnamed {
            get {
                return ResourceManager.GetString("Unnamed", resourceCulture);
            }
        }
        
        public static string NewSource {
            get {
                return ResourceManager.GetString("NewSource", resourceCulture);
            }
        }
        
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        public static string PinActive {
            get {
                return ResourceManager.GetString("PinActive", resourceCulture);
            }
        }
        
        public static string FingerprintActive {
            get {
                return ResourceManager.GetString("FingerprintActive", resourceCulture);
            }
        }
        
        public static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        public static string PinSettings {
            get {
                return ResourceManager.GetString("PinSettings", resourceCulture);
            }
        }
        
        public static string EnablePin {
            get {
                return ResourceManager.GetString("EnablePin", resourceCulture);
            }
        }
        
        public static string DisablePin {
            get {
                return ResourceManager.GetString("DisablePin", resourceCulture);
            }
        }
        
        public static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        public static string OldPin {
            get {
                return ResourceManager.GetString("OldPin", resourceCulture);
            }
        }
        
        public static string NewPin {
            get {
                return ResourceManager.GetString("NewPin", resourceCulture);
            }
        }
        
        public static string RepeatNewPin {
            get {
                return ResourceManager.GetString("RepeatNewPin", resourceCulture);
            }
        }
        
        public static string UseFingerprint {
            get {
                return ResourceManager.GetString("UseFingerprint", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string PinToShort {
            get {
                return ResourceManager.GetString("PinToShort", resourceCulture);
            }
        }
        
        public static string NewPinsDontMatch {
            get {
                return ResourceManager.GetString("NewPinsDontMatch", resourceCulture);
            }
        }
        
        public static string OldPinWrong {
            get {
                return ResourceManager.GetString("OldPinWrong", resourceCulture);
            }
        }
        
        public static string UnlockTheApplication {
            get {
                return ResourceManager.GetString("UnlockTheApplication", resourceCulture);
            }
        }
        
        public static string ScanQrCode {
            get {
                return ResourceManager.GetString("ScanQrCode", resourceCulture);
            }
        }
        
        public static string AmountAndCurrency {
            get {
                return ResourceManager.GetString("AmountAndCurrency", resourceCulture);
            }
        }
        
        public static string VerifyInput {
            get {
                return ResourceManager.GetString("VerifyInput", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string NoSourcesDescriptionAdd {
            get {
                return ResourceManager.GetString("NoSourcesDescriptionAdd", resourceCulture);
            }
        }
        
        public static string GoToSourcesToAddAccount {
            get {
                return ResourceManager.GetString("GoToSourcesToAddAccount", resourceCulture);
            }
        }
        
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        public static string Manually {
            get {
                return ResourceManager.GetString("Manually", resourceCulture);
            }
        }
        
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        public static string AsCurrency {
            get {
                return ResourceManager.GetString("AsCurrency", resourceCulture);
            }
        }
        
        public static string DefaultView {
            get {
                return ResourceManager.GetString("DefaultView", resourceCulture);
            }
        }
        
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        public static string ManuallyAdded {
            get {
                return ResourceManager.GetString("ManuallyAdded", resourceCulture);
            }
        }
        
        public static string AddressAdded {
            get {
                return ResourceManager.GetString("AddressAdded", resourceCulture);
            }
        }
        
        public static string BittrexAdded {
            get {
                return ResourceManager.GetString("BittrexAdded", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string LoadRatesAndBalancesOnStartup {
            get {
                return ResourceManager.GetString("LoadRatesAndBalancesOnStartup", resourceCulture);
            }
        }
        
        public static string RoundNumbers {
            get {
                return ResourceManager.GetString("RoundNumbers", resourceCulture);
            }
        }
        
        public static string OtherwiseTruncate {
            get {
                return ResourceManager.GetString("OtherwiseTruncate", resourceCulture);
            }
        }
        
        public static string RepositoryAlreadyAdded {
            get {
                return ResourceManager.GetString("RepositoryAlreadyAdded", resourceCulture);
            }
        }
        
        public static string MainCurrencies {
            get {
                return ResourceManager.GetString("MainCurrencies", resourceCulture);
            }
        }
        
        public static string FurtherCurrencies {
            get {
                return ResourceManager.GetString("FurtherCurrencies", resourceCulture);
            }
        }
        
        public static string AddMainCurrencies {
            get {
                return ResourceManager.GetString("AddMainCurrencies", resourceCulture);
            }
        }
        
        public static string AddFurtherCurrencies {
            get {
                return ResourceManager.GetString("AddFurtherCurrencies", resourceCulture);
            }
        }
        
        public static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        public static string IsEqualTo {
            get {
                return ResourceManager.GetString("IsEqualTo", resourceCulture);
            }
        }
        
        public static string AddressOrXpub {
            get {
                return ResourceManager.GetString("AddressOrXpub", resourceCulture);
            }
        }
        
        public static string AllCurrenciesFromAccounts {
            get {
                return ResourceManager.GetString("AllCurrenciesFromAccounts", resourceCulture);
            }
        }
        
        public static string AdditionalCurrencies {
            get {
                return ResourceManager.GetString("AdditionalCurrencies", resourceCulture);
            }
        }
        
        public static string RatesCurrenciesInfo {
            get {
                return ResourceManager.GetString("RatesCurrenciesInfo", resourceCulture);
            }
        }
        
        public static string CurrenciesForRateView {
            get {
                return ResourceManager.GetString("CurrenciesForRateView", resourceCulture);
            }
        }
        
        public static string NoCurrencies {
            get {
                return ResourceManager.GetString("NoCurrencies", resourceCulture);
            }
        }
        
        public static string OneCurrency {
            get {
                return ResourceManager.GetString("OneCurrency", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string Abbreviation {
            get {
                return ResourceManager.GetString("Abbreviation", resourceCulture);
            }
        }
        
        public static string Algorithm {
            get {
                return ResourceManager.GetString("Algorithm", resourceCulture);
            }
        }
        
        public static string Blocktime {
            get {
                return ResourceManager.GetString("Blocktime", resourceCulture);
            }
        }
        
        public static string Hashrate {
            get {
                return ResourceManager.GetString("Hashrate", resourceCulture);
            }
        }
        
        public static string Difficulty {
            get {
                return ResourceManager.GetString("Difficulty", resourceCulture);
            }
        }
        
        public static string BlockHeight {
            get {
                return ResourceManager.GetString("BlockHeight", resourceCulture);
            }
        }
        
        public static string CoinSupply {
            get {
                return ResourceManager.GetString("CoinSupply", resourceCulture);
            }
        }
        
        public static string ProofOfWork {
            get {
                return ResourceManager.GetString("ProofOfWork", resourceCulture);
            }
        }
        
        public static string ProofOfStake {
            get {
                return ResourceManager.GetString("ProofOfStake", resourceCulture);
            }
        }
        
        public static string GHps {
            get {
                return ResourceManager.GetString("GHps", resourceCulture);
            }
        }
        
        public static string unitSecond {
            get {
                return ResourceManager.GetString("unitSecond", resourceCulture);
            }
        }
        
        public static string MarketCap {
            get {
                return ResourceManager.GetString("MarketCap", resourceCulture);
            }
        }
        
        public static string ProofOfWorkAndState {
            get {
                return ResourceManager.GetString("ProofOfWorkAndState", resourceCulture);
            }
        }
        
        public static string BlockExplorer {
            get {
                return ResourceManager.GetString("BlockExplorer", resourceCulture);
            }
        }
        
        public static string BitcoinCanNotBeUnstared {
            get {
                return ResourceManager.GetString("BitcoinCanNotBeUnstared", resourceCulture);
            }
        }
        
        public static string BitcoinCanNotBeRemoved {
            get {
                return ResourceManager.GetString("BitcoinCanNotBeRemoved", resourceCulture);
            }
        }
    }
}
