// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyCC.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class I18N {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyCC.Forms.Resources.I18N", typeof(I18N).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        public static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        public static string AdditionalCurrencies {
            get {
                return ResourceManager.GetString("AdditionalCurrencies", resourceCulture);
            }
        }
        
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        public static string AddressAdded {
            get {
                return ResourceManager.GetString("AddressAdded", resourceCulture);
            }
        }
        
        public static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        public static string CoinAlgorithm {
            get {
                return ResourceManager.GetString("CoinAlgorithm", resourceCulture);
            }
        }
        
        public static string AllCurrenciesFromAccounts {
            get {
                return ResourceManager.GetString("AllCurrenciesFromAccounts", resourceCulture);
            }
        }
        
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        public static string BittrexKey {
            get {
                return ResourceManager.GetString("BittrexKey", resourceCulture);
            }
        }
        
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        public static string AppNameLong {
            get {
                return ResourceManager.GetString("AppNameLong", resourceCulture);
            }
        }
        
        public static string AsCurrency {
            get {
                return ResourceManager.GetString("AsCurrency", resourceCulture);
            }
        }
        
        public static string Assets {
            get {
                return ResourceManager.GetString("Assets", resourceCulture);
            }
        }
        
        public static string BitcoinCanNotBeRemoved {
            get {
                return ResourceManager.GetString("BitcoinCanNotBeRemoved", resourceCulture);
            }
        }
        
        public static string Bittrex {
            get {
                return ResourceManager.GetString("Bittrex", resourceCulture);
            }
        }
        
        public static string BittrexAdded {
            get {
                return ResourceManager.GetString("BittrexAdded", resourceCulture);
            }
        }
        
        public static string CoinExplorer {
            get {
                return ResourceManager.GetString("CoinExplorer", resourceCulture);
            }
        }
        
        public static string CoinBlockHeight {
            get {
                return ResourceManager.GetString("CoinBlockHeight", resourceCulture);
            }
        }
        
        public static string CoinBlockReward {
            get {
                return ResourceManager.GetString("CoinBlockReward", resourceCulture);
            }
        }
        
        public static string CoinBlocktime {
            get {
                return ResourceManager.GetString("CoinBlocktime", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        public static string CoinSupply {
            get {
                return ResourceManager.GetString("CoinSupply", resourceCulture);
            }
        }
        
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        public static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        public static string CurrenciesForRateView {
            get {
                return ResourceManager.GetString("CurrenciesForRateView", resourceCulture);
            }
        }
        
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        public static string DefaultPageInfo {
            get {
                return ResourceManager.GetString("DefaultPageInfo", resourceCulture);
            }
        }
        
        public static string DefaultView {
            get {
                return ResourceManager.GetString("DefaultView", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        public static string CoinDifficulty {
            get {
                return ResourceManager.GetString("CoinDifficulty", resourceCulture);
            }
        }
        
        public static string DisablePin {
            get {
                return ResourceManager.GetString("DisablePin", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        public static string EnablePin {
            get {
                return ResourceManager.GetString("EnablePin", resourceCulture);
            }
        }
        
        public static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        public static string FetchingNoSuccessText {
            get {
                return ResourceManager.GetString("FetchingNoSuccessText", resourceCulture);
            }
        }
        
        public static string FingerprintActive {
            get {
                return ResourceManager.GetString("FingerprintActive", resourceCulture);
            }
        }
        
        public static string Further {
            get {
                return ResourceManager.GetString("Further", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        public static string GHps {
            get {
                return ResourceManager.GetString("GHps", resourceCulture);
            }
        }
        
        public static string GoToSourcesToAddAccount {
            get {
                return ResourceManager.GetString("GoToSourcesToAddAccount", resourceCulture);
            }
        }
        
        public static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        public static string CoinHashrate {
            get {
                return ResourceManager.GetString("CoinHashrate", resourceCulture);
            }
        }
        
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        public static string IsEqualTo {
            get {
                return ResourceManager.GetString("IsEqualTo", resourceCulture);
            }
        }
        
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        public static string LoadRatesAndBalancesOnStartup {
            get {
                return ResourceManager.GetString("LoadRatesAndBalancesOnStartup", resourceCulture);
            }
        }
        
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        public static string Manually {
            get {
                return ResourceManager.GetString("Manually", resourceCulture);
            }
        }
        
        public static string ManuallyAdded {
            get {
                return ResourceManager.GetString("ManuallyAdded", resourceCulture);
            }
        }
        
        public static string CoinMarketCap {
            get {
                return ResourceManager.GetString("CoinMarketCap", resourceCulture);
            }
        }
        
        public static string CoinSupplyMax {
            get {
                return ResourceManager.GetString("CoinSupplyMax", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        public static string NewPin {
            get {
                return ResourceManager.GetString("NewPin", resourceCulture);
            }
        }
        
        public static string NewPinsDontMatch {
            get {
                return ResourceManager.GetString("NewPinsDontMatch", resourceCulture);
            }
        }
        
        public static string NewSource {
            get {
                return ResourceManager.GetString("NewSource", resourceCulture);
            }
        }
        
        public static string NoAccounts {
            get {
                return ResourceManager.GetString("NoAccounts", resourceCulture);
            }
        }
        
        public static string NoCurrencies {
            get {
                return ResourceManager.GetString("NoCurrencies", resourceCulture);
            }
        }
        
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        public static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        public static string NoSourcesDescriptionAdd {
            get {
                return ResourceManager.GetString("NoSourcesDescriptionAdd", resourceCulture);
            }
        }
        
        public static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string OldPin {
            get {
                return ResourceManager.GetString("OldPin", resourceCulture);
            }
        }
        
        public static string OldPinWrong {
            get {
                return ResourceManager.GetString("OldPinWrong", resourceCulture);
            }
        }
        
        public static string OneAccount {
            get {
                return ResourceManager.GetString("OneAccount", resourceCulture);
            }
        }
        
        public static string OneCurrency {
            get {
                return ResourceManager.GetString("OneCurrency", resourceCulture);
            }
        }
        
        public static string OneSource {
            get {
                return ResourceManager.GetString("OneSource", resourceCulture);
            }
        }
        
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        public static string OnlyThreeCurrenciesCanBeStared {
            get {
                return ResourceManager.GetString("OnlyThreeCurrenciesCanBeStared", resourceCulture);
            }
        }
        
        public static string OtherwiseTruncate {
            get {
                return ResourceManager.GetString("OtherwiseTruncate", resourceCulture);
            }
        }
        
        public static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        public static string PinActive {
            get {
                return ResourceManager.GetString("PinActive", resourceCulture);
            }
        }
        
        public static string PinToShort {
            get {
                return ResourceManager.GetString("PinToShort", resourceCulture);
            }
        }
        
        public static string CoinProofOfStake {
            get {
                return ResourceManager.GetString("CoinProofOfStake", resourceCulture);
            }
        }
        
        public static string CoinProofOfWork {
            get {
                return ResourceManager.GetString("CoinProofOfWork", resourceCulture);
            }
        }
        
        public static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        public static string RatesCurrenciesInfo {
            get {
                return ResourceManager.GetString("RatesCurrenciesInfo", resourceCulture);
            }
        }
        
        public static string ReferenceCurrencies {
            get {
                return ResourceManager.GetString("ReferenceCurrencies", resourceCulture);
            }
        }
        
        public static string ReferenceCurrencyInfoP1 {
            get {
                return ResourceManager.GetString("ReferenceCurrencyInfoP1", resourceCulture);
            }
        }
        
        public static string ReferenceCurrencyInfoP2 {
            get {
                return ResourceManager.GetString("ReferenceCurrencyInfoP2", resourceCulture);
            }
        }
        
        public static string RefreshOnStartup {
            get {
                return ResourceManager.GetString("RefreshOnStartup", resourceCulture);
            }
        }
        
        public static string RepeatNewPin {
            get {
                return ResourceManager.GetString("RepeatNewPin", resourceCulture);
            }
        }
        
        public static string RepositoryAlreadyAdded {
            get {
                return ResourceManager.GetString("RepositoryAlreadyAdded", resourceCulture);
            }
        }
        
        public static string RoundNumbers {
            get {
                return ResourceManager.GetString("RoundNumbers", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string ScanQrCode {
            get {
                return ResourceManager.GetString("ScanQrCode", resourceCulture);
            }
        }
        
        public static string SearchCurrencies {
            get {
                return ResourceManager.GetString("SearchCurrencies", resourceCulture);
            }
        }
        
        public static string BittrexSecret {
            get {
                return ResourceManager.GetString("BittrexSecret", resourceCulture);
            }
        }
        
        public static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        public static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        public static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        public static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        public static string UnitSecond {
            get {
                return ResourceManager.GetString("UnitSecond", resourceCulture);
            }
        }
        
        public static string Unnamed {
            get {
                return ResourceManager.GetString("Unnamed", resourceCulture);
            }
        }
        
        public static string UseFingerprint {
            get {
                return ResourceManager.GetString("UseFingerprint", resourceCulture);
            }
        }
        
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        public static string VerifyInput {
            get {
                return ResourceManager.GetString("VerifyInput", resourceCulture);
            }
        }
        
        public static string UnlockApplication {
            get {
                return ResourceManager.GetString("UnlockApplication", resourceCulture);
            }
        }
        
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string ShowQrCode {
            get {
                return ResourceManager.GetString("ShowQrCode", resourceCulture);
            }
        }
        
        public static string EnableAccount {
            get {
                return ResourceManager.GetString("EnableAccount", resourceCulture);
            }
        }
        
        public static string EnabledInOverview {
            get {
                return ResourceManager.GetString("EnabledInOverview", resourceCulture);
            }
        }
        
        public static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        public static string PreferredBitcoinRate {
            get {
                return ResourceManager.GetString("PreferredBitcoinRate", resourceCulture);
            }
        }
        
        public static string AvailableRates {
            get {
                return ResourceManager.GetString("AvailableRates", resourceCulture);
            }
        }
        
        public static string InfoNoDirectRate {
            get {
                return ResourceManager.GetString("InfoNoDirectRate", resourceCulture);
            }
        }
        
        public static string AreEqualTo {
            get {
                return ResourceManager.GetString("AreEqualTo", resourceCulture);
            }
        }
        
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        public static string QrCode {
            get {
                return ResourceManager.GetString("QrCode", resourceCulture);
            }
        }
        
        public static string RefreshingDots {
            get {
                return ResourceManager.GetString("RefreshingDots", resourceCulture);
            }
        }
        
        public static string AddRate {
            get {
                return ResourceManager.GetString("AddRate", resourceCulture);
            }
        }
        
        public static string AddReferenceCurrency {
            get {
                return ResourceManager.GetString("AddReferenceCurrency", resourceCulture);
            }
        }
        
        public static string AdditionalRates {
            get {
                return ResourceManager.GetString("AdditionalRates", resourceCulture);
            }
        }
        
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        public static string DisabledAccounts {
            get {
                return ResourceManager.GetString("DisabledAccounts", resourceCulture);
            }
        }
        
        public static string LastChange {
            get {
                return ResourceManager.GetString("LastChange", resourceCulture);
            }
        }
        
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        public static string AllCurrencies {
            get {
                return ResourceManager.GetString("AllCurrencies", resourceCulture);
            }
        }
        
        public static string AvailableCurrencies {
            get {
                return ResourceManager.GetString("AvailableCurrencies", resourceCulture);
            }
        }
        
        public static string Cryptocurrencies {
            get {
                return ResourceManager.GetString("Cryptocurrencies", resourceCulture);
            }
        }
        
        public static string FiatCurrencies {
            get {
                return ResourceManager.GetString("FiatCurrencies", resourceCulture);
            }
        }
        
        public static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        public static string BalanceAvailable {
            get {
                return ResourceManager.GetString("BalanceAvailable", resourceCulture);
            }
        }
        
        public static string BalanceAvailableAddress {
            get {
                return ResourceManager.GetString("BalanceAvailableAddress", resourceCulture);
            }
        }
        
        public static string BalanceAvailableBittrex {
            get {
                return ResourceManager.GetString("BalanceAvailableBittrex", resourceCulture);
            }
        }
        
        public static string ErrorRefreshingNotPossibleWithoutInternet {
            get {
                return ResourceManager.GetString("ErrorRefreshingNotPossibleWithoutInternet", resourceCulture);
            }
        }
        
        public static string NoInternetAccess {
            get {
                return ResourceManager.GetString("NoInternetAccess", resourceCulture);
            }
        }
        
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        public static string LoadingCurrencies {
            get {
                return ResourceManager.GetString("LoadingCurrencies", resourceCulture);
            }
        }
        
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        public static string PrivacyLinkId {
            get {
                return ResourceManager.GetString("PrivacyLinkId", resourceCulture);
            }
        }
        
        public static string AssetsColumnToHide {
            get {
                return ResourceManager.GetString("AssetsColumnToHide", resourceCulture);
            }
        }
        
        public static string AssetsColumnToHideDescription {
            get {
                return ResourceManager.GetString("AssetsColumnToHideDescription", resourceCulture);
            }
        }
        
        public static string InitialiseApp {
            get {
                return ResourceManager.GetString("InitialiseApp", resourceCulture);
            }
        }
        
        public static string InternetIsNeededForInitialisation {
            get {
                return ResourceManager.GetString("InternetIsNeededForInitialisation", resourceCulture);
            }
        }
        
        public static string LoadingAvailableRatesFrom {
            get {
                return ResourceManager.GetString("LoadingAvailableRatesFrom", resourceCulture);
            }
        }
        
        public static string LoadingCurrenciesFrom {
            get {
                return ResourceManager.GetString("LoadingCurrenciesFrom", resourceCulture);
            }
        }
        
        public static string LoadingRates {
            get {
                return ResourceManager.GetString("LoadingRates", resourceCulture);
            }
        }
        
        public static string ReferenceValue {
            get {
                return ResourceManager.GetString("ReferenceValue", resourceCulture);
            }
        }
        
        public static string SavingSource {
            get {
                return ResourceManager.GetString("SavingSource", resourceCulture);
            }
        }
    }
}
