// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MyCryptos.Forms.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18N_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18N_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MyCryptos.Forms.Resources.I18N.de", typeof(I18N_de).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AddCoinTitle {
            get {
                return ResourceManager.GetString("AddCoinTitle", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static string AddAccountTitle {
            get {
                return ResourceManager.GetString("AddAccountTitle", resourceCulture);
            }
        }
        
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Coins {
            get {
                return ResourceManager.GetString("Coins", resourceCulture);
            }
        }
        
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string CurrencyExample {
            get {
                return ResourceManager.GetString("CurrencyExample", resourceCulture);
            }
        }
        
        internal static string ValueExample {
            get {
                return ResourceManager.GetString("ValueExample", resourceCulture);
            }
        }
        
        internal static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        internal static string NewStorage {
            get {
                return ResourceManager.GetString("NewStorage", resourceCulture);
            }
        }
        
        internal static string DefaultStorage {
            get {
                return ResourceManager.GetString("DefaultStorage", resourceCulture);
            }
        }
        
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        internal static string LabelExample {
            get {
                return ResourceManager.GetString("LabelExample", resourceCulture);
            }
        }
        
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string NoAccounts {
            get {
                return ResourceManager.GetString("NoAccounts", resourceCulture);
            }
        }
        
        internal static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        internal static string Sources {
            get {
                return ResourceManager.GetString("Sources", resourceCulture);
            }
        }
        
        internal static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        internal static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        internal static string ReferenceCurrency {
            get {
                return ResourceManager.GetString("ReferenceCurrency", resourceCulture);
            }
        }
        
        internal static string AddActionChooseTitle {
            get {
                return ResourceManager.GetString("AddActionChooseTitle", resourceCulture);
            }
        }
        
        internal static string AddLocalAccount {
            get {
                return ResourceManager.GetString("AddLocalAccount", resourceCulture);
            }
        }
        
        internal static string SortOrder {
            get {
                return ResourceManager.GetString("SortOrder", resourceCulture);
            }
        }
        
        internal static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        internal static string ByValue {
            get {
                return ResourceManager.GetString("ByValue", resourceCulture);
            }
        }
        
        internal static string ByUnits {
            get {
                return ResourceManager.GetString("ByUnits", resourceCulture);
            }
        }
        
        internal static string NoExchangeRateFound {
            get {
                return ResourceManager.GetString("NoExchangeRateFound", resourceCulture);
            }
        }
        
        internal static string RefreshingDots {
            get {
                return ResourceManager.GetString("RefreshingDots", resourceCulture);
            }
        }
        
        internal static string SortDirection {
            get {
                return ResourceManager.GetString("SortDirection", resourceCulture);
            }
        }
        
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        internal static string AutomaticallyRefresh {
            get {
                return ResourceManager.GetString("AutomaticallyRefresh", resourceCulture);
            }
        }
        
        internal static string RefreshOnStartup {
            get {
                return ResourceManager.GetString("RefreshOnStartup", resourceCulture);
            }
        }
        
        internal static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        internal static string SearchCurrencies {
            get {
                return ResourceManager.GetString("SearchCurrencies", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string LocalAccount {
            get {
                return ResourceManager.GetString("LocalAccount", resourceCulture);
            }
        }
        
        internal static string DifferentCoinsCount {
            get {
                return ResourceManager.GetString("DifferentCoinsCount", resourceCulture);
            }
        }
        
        internal static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        internal static string ExchangeRate {
            get {
                return ResourceManager.GetString("ExchangeRate", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        internal static string SecretApiKey {
            get {
                return ResourceManager.GetString("SecretApiKey", resourceCulture);
            }
        }
        
        internal static string AddRepositoryTitle {
            get {
                return ResourceManager.GetString("AddRepositoryTitle", resourceCulture);
            }
        }
        
        internal static string Bittrex {
            get {
                return ResourceManager.GetString("Bittrex", resourceCulture);
            }
        }
        
        internal static string AddBittrexAcoount {
            get {
                return ResourceManager.GetString("AddBittrexAcoount", resourceCulture);
            }
        }
        
        internal static string AddSource {
            get {
                return ResourceManager.GetString("AddSource", resourceCulture);
            }
        }
        
        internal static string GrantAccess {
            get {
                return ResourceManager.GetString("GrantAccess", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string FetchingNoSuccessText {
            get {
                return ResourceManager.GetString("FetchingNoSuccessText", resourceCulture);
            }
        }
        
        internal static string Testing {
            get {
                return ResourceManager.GetString("Testing", resourceCulture);
            }
        }
        
        internal static string Fetching {
            get {
                return ResourceManager.GetString("Fetching", resourceCulture);
            }
        }
        
        internal static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        internal static string Deleting {
            get {
                return ResourceManager.GetString("Deleting", resourceCulture);
            }
        }
        
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        internal static string SelectRepositoryType {
            get {
                return ResourceManager.GetString("SelectRepositoryType", resourceCulture);
            }
        }
        
        internal static string BlockExperts {
            get {
                return ResourceManager.GetString("BlockExperts", resourceCulture);
            }
        }
        
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        internal static string AccountInformation {
            get {
                return ResourceManager.GetString("AccountInformation", resourceCulture);
            }
        }
        
        internal static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        internal static string BlockExpertsAccount {
            get {
                return ResourceManager.GetString("BlockExpertsAccount", resourceCulture);
            }
        }
        
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        internal static string NoCoins {
            get {
                return ResourceManager.GetString("NoCoins", resourceCulture);
            }
        }
        
        internal static string Blockchain {
            get {
                return ResourceManager.GetString("Blockchain", resourceCulture);
            }
        }
        
        internal static string BlockchainAccount {
            get {
                return ResourceManager.GetString("BlockchainAccount", resourceCulture);
            }
        }
        
        internal static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        internal static string Graph {
            get {
                return ResourceManager.GetString("Graph", resourceCulture);
            }
        }
        
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        internal static string Appeareance {
            get {
                return ResourceManager.GetString("Appeareance", resourceCulture);
            }
        }
        
        internal static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        internal static string AdditionalReferenceCurrency {
            get {
                return ResourceManager.GetString("AdditionalReferenceCurrency", resourceCulture);
            }
        }
        
        internal static string AddReferenceCurrency {
            get {
                return ResourceManager.GetString("AddReferenceCurrency", resourceCulture);
            }
        }
        
        internal static string PrimaryReferenceCurrency {
            get {
                return ResourceManager.GetString("PrimaryReferenceCurrency", resourceCulture);
            }
        }
        
        internal static string ReferenceCurrencies {
            get {
                return ResourceManager.GetString("ReferenceCurrencies", resourceCulture);
            }
        }
        
        internal static string Etherchain {
            get {
                return ResourceManager.GetString("Etherchain", resourceCulture);
            }
        }
        
        internal static string CryptoId {
            get {
                return ResourceManager.GetString("CryptoId", resourceCulture);
            }
        }
        
        internal static string OneAccount {
            get {
                return ResourceManager.GetString("OneAccount", resourceCulture);
            }
        }
        
        internal static string OneCoin {
            get {
                return ResourceManager.GetString("OneCoin", resourceCulture);
            }
        }
        
        internal static string OneSource {
            get {
                return ResourceManager.GetString("OneSource", resourceCulture);
            }
        }
        
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        internal static string LocalStorage {
            get {
                return ResourceManager.GetString("LocalStorage", resourceCulture);
            }
        }
        
        internal static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        internal static string AddWithAddress {
            get {
                return ResourceManager.GetString("AddWithAddress", resourceCulture);
            }
        }
        
        internal static string AddWithBittrexAccount {
            get {
                return ResourceManager.GetString("AddWithBittrexAccount", resourceCulture);
            }
        }
        
        internal static string Unnamed {
            get {
                return ResourceManager.GetString("Unnamed", resourceCulture);
            }
        }
        
        internal static string NewSource {
            get {
                return ResourceManager.GetString("NewSource", resourceCulture);
            }
        }
        
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        internal static string Pin {
            get {
                return ResourceManager.GetString("Pin", resourceCulture);
            }
        }
        
        internal static string PinActive {
            get {
                return ResourceManager.GetString("PinActive", resourceCulture);
            }
        }
        
        internal static string FingerprintActive {
            get {
                return ResourceManager.GetString("FingerprintActive", resourceCulture);
            }
        }
        
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        internal static string PinSettings {
            get {
                return ResourceManager.GetString("PinSettings", resourceCulture);
            }
        }
        
        internal static string EnablePin {
            get {
                return ResourceManager.GetString("EnablePin", resourceCulture);
            }
        }
        
        internal static string DisablePin {
            get {
                return ResourceManager.GetString("DisablePin", resourceCulture);
            }
        }
        
        internal static string ChangePin {
            get {
                return ResourceManager.GetString("ChangePin", resourceCulture);
            }
        }
        
        internal static string OldPin {
            get {
                return ResourceManager.GetString("OldPin", resourceCulture);
            }
        }
        
        internal static string NewPin {
            get {
                return ResourceManager.GetString("NewPin", resourceCulture);
            }
        }
        
        internal static string RepeatNewPin {
            get {
                return ResourceManager.GetString("RepeatNewPin", resourceCulture);
            }
        }
        
        internal static string UseFingerprint {
            get {
                return ResourceManager.GetString("UseFingerprint", resourceCulture);
            }
        }
        
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        internal static string PinToShort {
            get {
                return ResourceManager.GetString("PinToShort", resourceCulture);
            }
        }
        
        internal static string NewPinsDontMatch {
            get {
                return ResourceManager.GetString("NewPinsDontMatch", resourceCulture);
            }
        }
        
        internal static string OldPinWrong {
            get {
                return ResourceManager.GetString("OldPinWrong", resourceCulture);
            }
        }
        
        internal static string UnlockTheApplication {
            get {
                return ResourceManager.GetString("UnlockTheApplication", resourceCulture);
            }
        }
        
        internal static string ScanQrCode {
            get {
                return ResourceManager.GetString("ScanQrCode", resourceCulture);
            }
        }
        
        internal static string AmountAndCurrency {
            get {
                return ResourceManager.GetString("AmountAndCurrency", resourceCulture);
            }
        }
        
        internal static string VerifyInput {
            get {
                return ResourceManager.GetString("VerifyInput", resourceCulture);
            }
        }
        
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        internal static string ShowGraphOnStartup {
            get {
                return ResourceManager.GetString("ShowGraphOnStartup", resourceCulture);
            }
        }
        
        internal static string NoSourcesDescriptionAdd {
            get {
                return ResourceManager.GetString("NoSourcesDescriptionAdd", resourceCulture);
            }
        }
        
        internal static string GoToSourcesToAddAccount {
            get {
                return ResourceManager.GetString("GoToSourcesToAddAccount", resourceCulture);
            }
        }
        
        internal static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        internal static string Manually {
            get {
                return ResourceManager.GetString("Manually", resourceCulture);
            }
        }
        
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        internal static string AsCurrency {
            get {
                return ResourceManager.GetString("AsCurrency", resourceCulture);
            }
        }
        
        internal static string DefaultView {
            get {
                return ResourceManager.GetString("DefaultView", resourceCulture);
            }
        }
        
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        internal static string ManuallyAdded {
            get {
                return ResourceManager.GetString("ManuallyAdded", resourceCulture);
            }
        }
        
        internal static string AddressAdded {
            get {
                return ResourceManager.GetString("AddressAdded", resourceCulture);
            }
        }
        
        internal static string BittrexAdded {
            get {
                return ResourceManager.GetString("BittrexAdded", resourceCulture);
            }
        }
        
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        internal static string LoadRatesAndBalancesOnStartup {
            get {
                return ResourceManager.GetString("LoadRatesAndBalancesOnStartup", resourceCulture);
            }
        }
        
        internal static string RoundNumbers {
            get {
                return ResourceManager.GetString("RoundNumbers", resourceCulture);
            }
        }
        
        internal static string OtherwiseTruncate {
            get {
                return ResourceManager.GetString("OtherwiseTruncate", resourceCulture);
            }
        }
        
        internal static string RepositoryAlreadyAdded {
            get {
                return ResourceManager.GetString("RepositoryAlreadyAdded", resourceCulture);
            }
        }
        
        internal static string MainCurrencies {
            get {
                return ResourceManager.GetString("MainCurrencies", resourceCulture);
            }
        }
        
        internal static string FurtherCurrencies {
            get {
                return ResourceManager.GetString("FurtherCurrencies", resourceCulture);
            }
        }
        
        internal static string AddMainCurrencies {
            get {
                return ResourceManager.GetString("AddMainCurrencies", resourceCulture);
            }
        }
        
        internal static string AddFurtherCurrencies {
            get {
                return ResourceManager.GetString("AddFurtherCurrencies", resourceCulture);
            }
        }
        
        internal static string Rates {
            get {
                return ResourceManager.GetString("Rates", resourceCulture);
            }
        }
        
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        internal static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        internal static string IsEqualTo {
            get {
                return ResourceManager.GetString("IsEqualTo", resourceCulture);
            }
        }
        
        internal static string AddressOrXpub {
            get {
                return ResourceManager.GetString("AddressOrXpub", resourceCulture);
            }
        }
    }
}
